stages:
  - build
  - notice

build-ubuntu:
  stage: build
  tags:
    - ubuntu
  script:
    - chmod +x ./oneclick/start-crewclaw.sh
    - ./oneclick/start-crewclaw.sh
  only:
    - develop

build-windows:
  stage: build
  tags:
    - windows
  script:
    - .\oneclick\start-crewclaw.ps1
  only:
    - wh1
    - develop


notice:
  stage: notice
  tags: 
    - develop
  script:
    - chmod +x ./scripts/notice.sh
    - ./scripts/notice.sh
  when: always
  allow_failure: true
  only:
    - wh1
    - develop
